services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./api/src:/app/src
    networks:
      - app
  api:
    build: ./api
    depends_on:
      - mongo
    restart: always
    ports:
      - 3000:3000
    networks:
      - app

networks:
  app:
    driver: bridge
